version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgis_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    name: postgres_network

volumes:
  postgis_data: